-- supabase_migration_004.sql — 英文版（v6）
-- 需先執行 supabase_setup.sql；建議依序執行 002、003、004。可重複執行（idempotent）。
-- 1) ai_tools 新增 description_en、key_features_en，並填入 498 筆英文描述（只填空白欄位，不覆蓋你之後手動修改的內容）
-- 2) 全文搜尋欄位 search_tsv 納入英文描述（重建產生欄位與索引）
-- 3) diagnoses 新增 locale（'zh' | 'en'，舊資料預設 'zh'），AI 診斷快取依語言區分
begin;

alter table public.ai_tools add column if not exists description_en text;
alter table public.ai_tools add column if not exists key_features_en jsonb not null default '[]'::jsonb;

update public.ai_tools t set
  description_en = coalesce(nullif(btrim(t.description_en), ''), v.description_en),
  key_features_en = case when t.key_features_en is null or t.key_features_en = '[]'::jsonb then v.key_features_en else t.key_features_en end
from (values
  ('chatgpt', 'OpenAI''s general-purpose conversational AI assistant with text, image, voice and file analysis.', '["Multimodal chat", "Deep research", "Custom GPTs", "Code execution"]'::jsonb),
  ('claude', 'AI assistant from Anthropic, strong at long-document understanding, writing and coding.', '["Long context", "Artifacts", "Projects", "Coding help"]'::jsonb),
  ('gemini', 'Google''s multimodal AI assistant integrated with Google services.', '["Multimodal", "Google Workspace integration", "Deep research"]'::jsonb),
  ('copilot-microsoft', 'Microsoft''s AI assistant built into Windows and Office.', '["Web search", "Office integration", "Image generation"]'::jsonb),
  ('grok', 'AI assistant from xAI with real-time information from the X platform.', '["Real-time information", "Image generation", "Voice mode"]'::jsonb),
  ('deepseek', 'Conversational AI from China''s DeepSeek, with open model weights.', '["Reasoning mode", "Web search", "Open weights"]'::jsonb),
  ('meta-ai', 'Meta''s AI assistant, integrated into WhatsApp, Instagram and other apps.', '["Social app integration", "Image generation"]'::jsonb),
  ('mistral-le-chat', 'Chat assistant from France''s Mistral AI.', '["Fast answers", "Web search", "Document analysis"]'::jsonb),
  ('qwen', 'Alibaba''s Tongyi Qwen chat platform.', '["Multimodal", "Open-weight models"]'::jsonb),
  ('kimi', 'Long-context AI assistant from Moonshot AI.', '["Long context", "File reading", "Search"]'::jsonb),
  ('poe', 'Quora''s multi-model chat platform giving access to AI models from many providers.', '["Model switching", "Custom bots"]'::jsonb),
  ('character-ai', 'AI platform for chatting with a wide range of virtual characters.', '["Custom characters", "Voice chat"]'::jsonb),
  ('huggingchat', 'Hugging Face''s chat interface for open-source models.', '["Multiple open-source models", "Open-source interface"]'::jsonb),
  ('perplexity', 'AI answer engine that cites its sources.', '["Cited sources", "Deep research", "Model choice"]'::jsonb),
  ('you-com', 'AI search and research assistant platform.', '["AI search", "Research mode"]'::jsonb),
  ('consensus', 'AI search engine grounded in academic papers.', '["Paper search", "Consensus meter"]'::jsonb),
  ('elicit', 'Research assistant for literature reviews and data extraction from papers.', '["Literature search", "Data extraction", "Systematic reviews"]'::jsonb),
  ('notebooklm', 'Google''s source-grounded research notebook that can generate audio overviews.', '["Q&A over sources", "Audio overviews", "Mind maps"]'::jsonb),
  ('scispace', 'AI tool for reading and understanding academic papers.', '["Paper explanations", "Literature search"]'::jsonb),
  ('felo', 'Multilingual AI search engine.', '["Multilingual search", "Slide generation"]'::jsonb),
  ('midjourney', 'AI image generation service known for high-quality artistic styles.', '["Text-to-image", "Style references", "Video generation"]'::jsonb),
  ('dall-e', 'OpenAI''s image generation model, available inside ChatGPT.', '["Text-to-image", "Image editing"]'::jsonb),
  ('stable-diffusion', 'Stability AI''s open-weight image generation model.', '["Open weights", "Run locally", "Community models"]'::jsonb),
  ('leonardo', 'AI image generation platform suited to game and design assets.', '["Multiple models", "Realtime canvas", "Video"]'::jsonb),
  ('ideogram', 'AI image generator known for rendering text inside images.', '["Text rendering", "Style options", "Canvas editing"]'::jsonb),
  ('flux', 'Black Forest Labs'' family of high-quality image generation models.', '["High-quality images", "Some open weights", "API"]'::jsonb),
  ('adobe-firefly', 'Adobe''s commercially safe AI image and video generation tool.', '["Text-to-image", "Generative Fill", "Creative Cloud integration"]'::jsonb),
  ('krea', 'Real-time AI image generation and enhancement platform.', '["Real-time generation", "Image upscaling", "Video"]'::jsonb),
  ('playground', 'AI generation tool focused on graphic design.', '["Design templates", "Image generation"]'::jsonb),
  ('civitai', 'Community platform for sharing and using Stable Diffusion and other models.', '["Model sharing", "Online generation"]'::jsonb),
  ('runway', 'Professional AI video generation and editing platform.', '["Text/image-to-video", "Video editing tools"]'::jsonb),
  ('sora', 'OpenAI''s text-to-video model and app.', '["Text-to-video", "Remix"]'::jsonb),
  ('veo', 'Google''s video generation model, available through Flow and Gemini.', '["Text-to-video", "Native audio"]'::jsonb),
  ('pika', 'Easy-to-use AI video generator.', '["Effects", "Image-to-video"]'::jsonb),
  ('kling', 'AI video generation platform from Kuaishou.', '["High-quality video", "Lip sync", "Image generation"]'::jsonb),
  ('luma', 'Luma AI''s video and image generation platform.', '["Video generation", "Image generation"]'::jsonb),
  ('hailuo', 'AI video generator from MiniMax.', '["Text-to-video", "Image-to-video"]'::jsonb),
  ('synthesia', 'Platform for producing corporate videos with AI avatars.', '["AI avatars", "Multilingual voiceover", "Templates"]'::jsonb),
  ('heygen', 'AI avatar video and video translation platform.', '["Avatars", "Video translation", "Lip sync"]'::jsonb),
  ('descript', 'AI audio and video editor that lets you edit via the transcript.', '["Transcript-based editing", "Filler-word removal", "AI voices"]'::jsonb),
  ('capcut', 'ByteDance''s video editor with many built-in AI features.', '["Auto captions", "AI effects", "Templates"]'::jsonb),
  ('opus-clip', 'AI tool that automatically turns long videos into short clips.', '["Auto highlights", "Captions", "Virality score"]'::jsonb),
  ('elevenlabs', 'Realistic AI text-to-speech and voice cloning platform.', '["Text-to-speech", "Voice cloning", "Dubbing"]'::jsonb),
  ('murf', 'AI voiceover and narration tool for commercial use.', '["Multilingual voices", "Video voiceover"]'::jsonb),
  ('otter', 'AI meeting notes and real-time transcription tool.', '["Live transcription", "Meeting summaries", "Zoom integration"]'::jsonb),
  ('whisper', 'OpenAI''s open-source speech recognition model.', '["Multilingual transcription", "Translation", "Run locally"]'::jsonb),
  ('adobe-podcast', 'Adobe''s AI audio enhancement and recording tool.', '["Speech enhancement", "Mic check"]'::jsonb),
  ('fireflies', 'AI assistant that records, transcribes and summarizes meetings.', '["Meeting recording", "Summaries", "CRM integration"]'::jsonb),
  ('suno', 'AI music platform that generates complete songs from text prompts.', '["Song generation", "Lyrics", "Vocals"]'::jsonb),
  ('udio', 'High-quality AI song generation platform.', '["Song generation", "Extend and remix"]'::jsonb),
  ('aiva', 'AI composition tool suited to soundtrack creation.', '["Style-based composition", "MIDI export"]'::jsonb),
  ('soundraw', 'AI music tool for customizable royalty-free tracks.', '["Royalty-free", "Length/mood adjustment"]'::jsonb),
  ('github-copilot', 'GitHub''s AI code completion and coding agent tool.', '["Code completion", "Chat", "Coding Agent"]'::jsonb),
  ('cursor', 'AI-first code editor.', '["Agent", "Tab completion", "Codebase understanding"]'::jsonb),
  ('windsurf', 'AI code editor with agentic capabilities.', '["Cascade agent", "Completion"]'::jsonb),
  ('claude-code', 'Anthropic''s terminal-based coding agent.', '["Terminal agent", "Multi-file editing", "Git integration"]'::jsonb),
  ('openai-codex', 'OpenAI''s cloud and CLI coding agent.', '["Cloud tasks", "CLI", "PR generation"]'::jsonb),
  ('replit', 'Online IDE with an AI agent that builds apps from natural language.', '["Replit Agent", "Deployment", "Collaboration"]'::jsonb),
  ('lovable', 'Builds full-stack web apps through conversation.', '["Full-stack generation", "Supabase integration", "Deployment"]'::jsonb),
  ('bolt', 'StackBlitz''s in-browser AI full-stack development tool.', '["In-browser development", "One-click deploy"]'::jsonb),
  ('v0', 'Vercel''s AI UI and app generator.', '["React/Next.js generation", "Deploy to Vercel"]'::jsonb),
  ('tabnine', 'Privacy-focused AI coding assistant for enterprises.', '["Private deployment", "Code completion"]'::jsonb),
  ('devin', 'Cognition''s autonomous AI software engineer.', '["Autonomous tasks", "Slack integration"]'::jsonb),
  ('codeium-jetbrains-ai', 'AI assistant and Junie agent built into JetBrains IDEs.', '["IDE integration", "Junie agent"]'::jsonb),
  ('grammarly', 'English grammar checker and AI writing assistant.', '["Grammar correction", "Tone adjustment", "Generative rewriting"]'::jsonb),
  ('jasper', 'AI content platform for enterprise marketing teams.', '["Brand voice", "Marketing templates", "Agents"]'::jsonb),
  ('copy-ai', 'AI platform for go-to-market workflows and marketing copy.', '["Workflows", "Copy templates"]'::jsonb),
  ('quillbot', 'AI paraphrasing, summarizing and grammar checking tool.', '["Paraphrasing", "Summarizing", "AI detection"]'::jsonb),
  ('writesonic', 'Content platform for SEO and AI search visibility.', '["SEO articles", "GEO tracking"]'::jsonb),
  ('surfer', 'AI-assisted SEO content optimization tool.', '["Content score", "Keyword suggestions"]'::jsonb),
  ('sudowrite', 'AI writing tool designed for fiction authors.', '["Story brainstorming", "Continuation", "Description expansion"]'::jsonb),
  ('notion-ai', 'AI writing, search and agent features built into the Notion workspace.', '["AI writing", "Workspace search", "Meeting notes"]'::jsonb),
  ('microsoft-365-copilot', 'Enterprise AI assistant integrated with Word, Excel, Outlook and more.', '["Office integration", "Teams meeting recaps"]'::jsonb),
  ('gemini-workspace', 'Gemini features built into Gmail, Docs and Sheets.', '["Gmail drafting", "Docs generation", "Meet notes"]'::jsonb),
  ('mem', 'Personal note-taking tool that organizes notes automatically with AI.', '["Auto-organization", "AI search"]'::jsonb),
  ('motion', 'AI calendar auto-scheduling and task management tool.', '["Auto-scheduling", "Project management"]'::jsonb),
  ('reclaim', 'Smart calendar that automatically protects focus time.', '["Habit scheduling", "Meeting scheduling"]'::jsonb),
  ('granola', 'AI meeting notes tool that works without a meeting bot.', '["Enhanced meeting notes", "Templates"]'::jsonb),
  ('chatpdf', 'Upload a PDF and ask questions about it in a chat.', '["PDF Q&A", "Page citations"]'::jsonb),
  ('canva', 'Online design platform with many built-in AI features.', '["Magic Design", "Text-to-image", "Background removal"]'::jsonb),
  ('figma-ai', 'AI design and prototype generation built into Figma.', '["Make prototype generation", "Layer renaming", "Search"]'::jsonb),
  ('photoroom', 'AI background removal and product photo editing tool.', '["Background removal", "AI backgrounds", "Batch processing"]'::jsonb),
  ('remove-bg', 'One-click AI image background removal.', '["Automatic background removal", "API"]'::jsonb),
  ('uizard', 'Generates UI prototypes from text or hand-drawn sketches.', '["Text-to-UI", "Sketch conversion"]'::jsonb),
  ('looka', 'AI logo and brand identity design tool.', '["Logo generation", "Brand kit"]'::jsonb),
  ('magnific', 'AI image upscaling and detail enhancement tool.', '["High-resolution upscaling", "Detail regeneration"]'::jsonb),
  ('gamma', 'Creates presentations, documents and web pages with AI.', '["One-click decks", "Web page generation", "PPT export"]'::jsonb),
  ('beautiful-ai', 'AI presentation tool with automatic layout.', '["Smart layouts", "Team templates"]'::jsonb),
  ('pitch', 'Collaborative presentation software with AI generation.', '["AI first drafts", "Team collaboration"]'::jsonb),
  ('napkin', 'Automatically turns text into diagrams and visuals.', '["Text-to-diagram", "Icons"]'::jsonb),
  ('zapier-ai', 'Automation platform connecting thousands of apps, including AI agents.', '["Zaps", "AI Agents", "Chatbots"]'::jsonb),
  ('make', 'Visual workflow automation platform.', '["Visual workflows", "AI modules"]'::jsonb),
  ('n8n', 'Self-hostable workflow automation and AI agent platform.', '["Self-hosting", "AI Agent node", "Code node"]'::jsonb),
  ('manus', 'General-purpose AI agent that carries out multi-step tasks autonomously.', '["Autonomous execution", "Browser control", "File outputs"]'::jsonb),
  ('chatgpt-agent', 'Agent mode in ChatGPT that uses a browser and tools to complete tasks.', '["Browser control", "Task execution"]'::jsonb),
  ('langchain', 'Open-source frameworks for building LLM applications and agents.', '["Agent framework", "LangSmith monitoring"]'::jsonb),
  ('dify', 'Open-source platform for building LLM apps and agents.', '["Visual workflows", "RAG", "Self-hosting"]'::jsonb),
  ('relevance-ai', 'No-code platform for building teams of AI agents.', '["Agent building", "Tool integrations"]'::jsonb),
  ('deepl', 'High-quality neural machine translation and writing tool.', '["Document translation", "DeepL Write", "API"]'::jsonb),
  ('google-translate', 'Free translation service supporting over 100 languages.', '["Text/voice/camera translation", "Offline translation"]'::jsonb),
  ('immersive-translate', 'Browser extension for bilingual side-by-side web page and PDF translation.', '["Bilingual view", "PDF translation", "Multiple engines"]'::jsonb),
  ('rask', 'AI video translation and dubbing tool.', '["Video translation", "Voice cloning", "Lip sync"]'::jsonb),
  ('julius', 'Analyzes data and creates charts through conversation.', '["Data analysis", "Visualization", "Python execution"]'::jsonb),
  ('powerbi-copilot', 'AI report building and Q&A built into Power BI.', '["Natural-language reports", "DAX help"]'::jsonb),
  ('tableau-ai', 'Tableau''s AI insights and natural-language analytics features.', '["Pulse insights", "Natural-language queries"]'::jsonb),
  ('hex', 'Collaborative data notebook with an AI assistant.', '["SQL/Python", "AI assistant", "Data apps"]'::jsonb),
  ('rows', 'Online spreadsheet with a built-in AI analyst.', '["AI analysis", "Data integrations"]'::jsonb),
  ('pi', 'Personal conversational assistant from Inflection AI.', '[]'::jsonb),
  ('chatbase', 'Build customer-support AI agents on your own data.', '[]'::jsonb),
  ('bing-image-creator', 'Microsoft''s free AI image generator.', '[]'::jsonb),
  ('vizcom', 'Design tool that turns sketches into renderings.', '[]'::jsonb),
  ('hostinger-ai', 'Hostinger''s AI web app builder.', '[]'::jsonb),
  ('spline', 'Web 3D design tool with AI features.', '[]'::jsonb),
  ('invideo', 'Generates complete videos from text prompts.', '[]'::jsonb),
  ('hedra', 'Generates talking character videos.', '[]'::jsonb),
  ('speechify', 'Text-to-speech app that reads text aloud.', '[]'::jsonb),
  ('tldv', 'Meeting recording and AI notes.', '[]'::jsonb),
  ('mubert', 'AI-generated royalty-free music.', '[]'::jsonb),
  ('llamaindex', 'Data and agent framework for LLMs.', '[]'::jsonb),
  ('liner', 'AI search for academic research.', '[]'::jsonb),
  ('paperpal', 'AI assistant for academic writing.', '[]'::jsonb),
  ('originality', 'AI content and plagiarism detection.', '[]'::jsonb),
  ('hubspot-breeze', 'HubSpot''s AI agents and assistant.', '[]'::jsonb),
  ('semrush', 'SEO and content marketing platform with AI tools.', '[]'::jsonb),
  ('harvey', 'Generative AI platform for law firms.', '[]'::jsonb),
  ('abridge', 'Clinical documentation AI for medical conversations.', '[]'::jsonb),
  ('hirevue', 'AI interviewing and recruiting platform.', '[]'::jsonb),
  ('bloomberg-gpt', 'AI search for financial market intelligence.', '[]'::jsonb),
  ('plus-ai', 'AI presentations for Google Slides and PowerPoint.', '[]'::jsonb),
  ('papago', 'NAVER''s translation service.', '[]'::jsonb),
  ('typeform-ai', 'Conversational forms with AI features.', '[]'::jsonb),
  ('doubao', 'AI assistant from ByteDance.', '[]'::jsonb),
  ('intercom-fin', 'Intercom''s AI customer service agent.', '[]'::jsonb),
  ('nightcafe', 'Multi-model AI art generation community.', '[]'::jsonb),
  ('khroma', 'AI color palette tool.', '[]'::jsonb),
  ('amazon-q', 'AWS''s AI assistant for software development.', '[]'::jsonb),
  ('meshy', 'Generates 3D models from text or images.', '[]'::jsonb),
  ('pictory', 'Turns articles and scripts into videos.', '[]'::jsonb),
  ('d-id', 'Creates talking digital avatars from photos.', '[]'::jsonb),
  ('fathom', 'Free AI meeting notes.', '[]'::jsonb),
  ('boomy', 'Quickly create and release songs.', '[]'::jsonb),
  ('crewai', 'Multi-agent collaboration framework and platform.', '[]'::jsonb),
  ('semantic-scholar', 'AI-powered search engine for academic papers.', '[]'::jsonb),
  ('jenni', 'AI assistant for writing papers.', '[]'::jsonb),
  ('undetectable', 'AI detection and text humanizing.', '[]'::jsonb),
  ('gong', 'AI for sales call analysis.', '[]'::jsonb),
  ('ahrefs', 'SEO analytics with AI content tools.', '[]'::jsonb),
  ('casetext', 'Thomson Reuters'' legal AI assistant.', '[]'::jsonb),
  ('nuance-dax', 'Microsoft''s clinical AI assistant.', '[]'::jsonb),
  ('eightfold', 'AI talent intelligence platform.', '[]'::jsonb),
  ('hebbia', 'AI analysis of financial documents.', '[]'::jsonb),
  ('slidesai', 'Turns text into Google Slides presentations.', '[]'::jsonb),
  ('reverso', 'Translation with in-context example sentences.', '[]'::jsonb),
  ('tableau-gpt', 'Search- and AI-driven analytics.', '[]'::jsonb),
  ('ernie', 'Baidu''s large language model chat product.', '[]'::jsonb),
  ('zendesk-ai', 'AI agents and assistants in the Zendesk customer service platform.', '[]'::jsonb),
  ('openart', 'Multi-model image generation and workflow platform.', '[]'::jsonb),
  ('designs-ai', 'AI design suite.', '[]'::jsonb),
  ('gemini-code-assist', 'Google''s AI coding assistant.', '[]'::jsonb),
  ('tripo', 'AI 3D model generation.', '[]'::jsonb),
  ('fliki', 'Text-to-video with voiceover.', '[]'::jsonb),
  ('colossyan', 'AI avatar videos for corporate training.', '[]'::jsonb),
  ('resemble', 'Voice cloning and deepfake detection.', '[]'::jsonb),
  ('read-ai', 'Meeting summaries and analytics.', '[]'::jsonb),
  ('beatoven', 'Generates background music for videos.', '[]'::jsonb),
  ('autogen', 'Microsoft''s open-source multi-agent framework.', '[]'::jsonb),
  ('research-rabbit', 'Visual literature discovery.', '[]'::jsonb),
  ('khanmigo', 'Khan Academy''s AI tutor.', '[]'::jsonb),
  ('wordtune', 'AI rewriting and writing assistant.', '[]'::jsonb),
  ('clay', 'AI sales list enrichment and outreach.', '[]'::jsonb),
  ('frase', 'SEO research and content generation.', '[]'::jsonb),
  ('spellbook', 'AI contract drafting inside Microsoft Word.', '[]'::jsonb),
  ('nabla', 'AI assistant for physicians.', '[]'::jsonb),
  ('paradox', 'Conversational recruiting assistant Olivia.', '[]'::jsonb),
  ('rogo', 'AI for financial analysis.', '[]'::jsonb),
  ('decktopus', 'AI presentation generator.', '[]'::jsonb),
  ('smartcat', 'Enterprise AI translation platform.', '[]'::jsonb),
  ('polymer', 'AI dashboards.', '[]'::jsonb),
  ('zhipu-chatglm', 'Zhipu AI''s chat assistant based on its GLM models.', '[]'::jsonb),
  ('ada', 'Enterprise AI customer service automation platform.', '[]'::jsonb),
  ('tensor-art', 'Online model-sharing and image generation platform.', '[]'::jsonb),
  ('microsoft-designer', 'Microsoft''s AI graphic design tool.', '[]'::jsonb),
  ('gemini-cli', 'Open-source AI agent for the terminal.', '[]'::jsonb),
  ('luma-genie', 'Luma''s text-to-3D generator.', '[]'::jsonb),
  ('veed', 'Online AI video editor.', '[]'::jsonb),
  ('elai', 'AI avatar video creation.', '[]'::jsonb),
  ('wellsaid', 'Enterprise-grade AI voiceover.', '[]'::jsonb),
  ('avoma', 'Meeting assistant and revenue intelligence.', '[]'::jsonb),
  ('stable-audio', 'Stability AI''s audio generation.', '[]'::jsonb),
  ('flowise', 'Open-source drag-and-drop LLM workflows.', '[]'::jsonb),
  ('connected-papers', 'Visual graphs of related papers.', '[]'::jsonb),
  ('duolingo-max', 'Language learning with AI roleplay conversations.', '[]'::jsonb),
  ('rytr', 'Affordable AI writing assistant.', '[]'::jsonb),
  ('apollo', 'Prospect database and AI outreach.', '[]'::jsonb),
  ('clearscope', 'Content optimization platform.', '[]'::jsonb),
  ('luminance', 'Legal AI for contract review.', '[]'::jsonb),
  ('freed', 'AI medical note-taking for clinicians.', '[]'::jsonb),
  ('textio', 'AI for writing job posts and performance feedback.', '[]'::jsonb),
  ('presentations-ai', 'AI presentation design.', '[]'::jsonb),
  ('lokalise-ai', 'Software localization platform with AI.', '[]'::jsonb),
  ('akkio', 'AI data analytics for agencies.', '[]'::jsonb),
  ('yuanbao', 'Tencent''s AI assistant, integrating Hunyuan and DeepSeek models.', '[]'::jsonb),
  ('tidio', 'Live chat for small businesses with the Lyro AI agent.', '[]'::jsonb),
  ('seaart', 'AI art generation and model community.', '[]'::jsonb),
  ('framer-ai', 'Website design and publishing tool with AI.', '[]'::jsonb),
  ('sourcegraph-cody', 'Sourcegraph''s coding agent.', '[]'::jsonb),
  ('kapwing', 'Collaborative online video editor.', '[]'::jsonb),
  ('tavus', 'Personalized AI video and conversational avatars.', '[]'::jsonb),
  ('taskade', 'Workspace for AI agents and task management.', '[]'::jsonb),
  ('loudly', 'AI music generation and music library.', '[]'::jsonb),
  ('langflow', 'Open-source visual AI workflow builder.', '[]'::jsonb),
  ('scite', 'Smart citation analysis.', '[]'::jsonb),
  ('anyword', 'Marketing copy with performance prediction.', '[]'::jsonb),
  ('outreach', 'AI sales execution platform.', '[]'::jsonb),
  ('marketmuse', 'AI content strategy.', '[]'::jsonb),
  ('donotpay', 'Consumer legal assistance.', '[]'::jsonb),
  ('teal', 'AI resume builder and job search tracker.', '[]'::jsonb),
  ('tickeron', 'AI trading signals.', '[]'::jsonb),
  ('prezi-ai', 'Dynamic presentations with AI.', '[]'::jsonb),
  ('crowdin', 'Localization management platform.', '[]'::jsonb),
  ('obviously-ai', 'No-code predictive models.', '[]'::jsonb),
  ('cohere', 'AI company offering enterprise LLMs and RAG.', '[]'::jsonb),
  ('sierra', 'Enterprise conversational AI agent platform.', '[]'::jsonb),
  ('dreamstudio', 'Stability AI''s online image generation interface.', '[]'::jsonb),
  ('relume', 'AI-generated sitemaps and wireframes.', '[]'::jsonb),
  ('continue', 'Open-source AI coding assistant for IDEs.', '[]'::jsonb),
  ('kaedim', '3D asset generation for games.', '[]'::jsonb),
  ('clipchamp', 'Microsoft''s online video editor.', '[]'::jsonb),
  ('vidnoz', 'Free AI avatar videos.', '[]'::jsonb),
  ('listnr', 'AI voiceover and podcast tool.', '[]'::jsonb),
  ('clickup-brain', 'AI built into ClickUp.', '[]'::jsonb),
  ('musicfy', 'AI voice conversion for singing.', '[]'::jsonb),
  ('gumloop', 'No-code AI automation.', '[]'::jsonb),
  ('undermind', 'Deep academic search agent.', '[]'::jsonb),
  ('photomath', 'Solve math problems by taking a photo.', '[]'::jsonb),
  ('hypotenuse', 'Product description generation for e-commerce.', '[]'::jsonb),
  ('lavender', 'AI coach for sales emails.', '[]'::jsonb),
  ('neuronwriter', 'Semantic SEO content editor.', '[]'::jsonb),
  ('lexis-ai', 'LexisNexis generative legal research.', '[]'::jsonb),
  ('glass-health', 'AI clinical decision support.', '[]'::jsonb),
  ('kickresume', 'AI resume generation.', '[]'::jsonb),
  ('danelfin', 'AI stock ratings.', '[]'::jsonb),
  ('slidesgo', 'Freepik''s AI presentations.', '[]'::jsonb),
  ('unbabel', 'AI plus human translation.', '[]'::jsonb),
  ('datarobot', 'Enterprise AI platform.', '[]'::jsonb),
  ('groq', 'High-speed LLM inference powered by LPU chips.', '[]'::jsonb),
  ('decagon', 'Enterprise AI customer service agents.', '[]'::jsonb),
  ('getimg', 'Versatile AI image generation tool.', '[]'::jsonb),
  ('galileo-stitch', 'Google''s tool for generating UI designs with AI.', '[]'::jsonb),
  ('cline', 'Open-source autonomous coding agent for VS Code.', '[]'::jsonb),
  ('rodin', 'High-quality 3D generation model.', '[]'::jsonb),
  ('lumen5', 'Turns blog posts into social videos.', '[]'::jsonb),
  ('deepbrain', 'AI avatar presenter videos.', '[]'::jsonb),
  ('voicemod', 'Real-time voice changer software.', '[]'::jsonb),
  ('asana-ai', 'AI work features in Asana.', '[]'::jsonb),
  ('riffusion', 'AI music creation.', '[]'::jsonb),
  ('lindy', 'Build AI assistants that automate work.', '[]'::jsonb),
  ('exa', 'Search API designed for AI.', '[]'::jsonb),
  ('writer', 'Enterprise generative AI platform.', '[]'::jsonb),
  ('regie', 'AI sales development agents.', '[]'::jsonb),
  ('koala', 'SEO article generation.', '[]'::jsonb),
  ('ironclad', 'AI contract lifecycle management.', '[]'::jsonb),
  ('ada-health', 'AI symptom checker app.', '[]'::jsonb),
  ('rezi', 'AI resume writing.', '[]'::jsonb),
  ('stocknews-finchat', 'AI investment research.', '[]'::jsonb),
  ('chronicle', 'Modern presentation tool.', '[]'::jsonb),
  ('lara', 'LLM-based translation from Translated.', '[]'::jsonb),
  ('databricks', 'Data and AI platform.', '[]'::jsonb),
  ('together-ai', 'Cloud platform for open-source model inference and fine-tuning.', '[]'::jsonb),
  ('lexica', 'AI image search and generation.', '[]'::jsonb),
  ('visily', 'AI wireframing and UI design tool.', '[]'::jsonb),
  ('roo-code', 'Open-source AI agent for VS Code.', '[]'::jsonb),
  ('polycam', 'Mobile 3D scanning and Gaussian splatting.', '[]'::jsonb),
  ('vidyo', 'Turns long videos into short clips, with social media management.', '[]'::jsonb),
  ('argil', 'Creates AI clone videos for creators.', '[]'::jsonb),
  ('krisp', 'AI noise cancellation for calls and meeting assistant.', '[]'::jsonb),
  ('monday-ai', 'AI features in monday.com.', '[]'::jsonb),
  ('landr', 'AI mastering and music tools.', '[]'::jsonb),
  ('bardeen', 'AI browser automation.', '[]'::jsonb),
  ('tavily', 'Search API for agents.', '[]'::jsonb),
  ('brainly', 'Learning community with AI answers.', '[]'::jsonb),
  ('hyperwrite', 'AI writing and agents.', '[]'::jsonb),
  ('11x', 'Digital sales workers.', '[]'::jsonb),
  ('seowriting', 'One-click SEO articles.', '[]'::jsonb),
  ('legora', 'Collaborative AI platform for lawyers.', '[]'::jsonb),
  ('k-health', 'AI-assisted telehealth.', '[]'::jsonb),
  ('final-round', 'AI interview assistance.', '[]'::jsonb),
  ('brex-ai', 'Corporate cards and expense management with AI.', '[]'::jsonb),
  ('mindmeister', 'Online mind mapping with AI.', '[]'::jsonb),
  ('elevenlabs-dubbing', 'AI multilingual dubbing for videos.', '[]'::jsonb),
  ('snowflake-cortex', 'LLM features built into Snowflake.', '[]'::jsonb),
  ('openrouter', 'Platform providing a unified API to many LLMs.', '[]'::jsonb),
  ('botpress', 'Platform for building LLM chatbots.', '[]'::jsonb),
  ('durable', 'Quickly builds small-business websites with AI.', '[]'::jsonb),
  ('aider', 'AI pair programming tool for the terminal.', '[]'::jsonb),
  ('masterpiece-x', 'Generates animatable 3D models.', '[]'::jsonb),
  ('submagic', 'AI captions and editing for short videos.', '[]'::jsonb),
  ('cleanvoice', 'Automatically removes filler words and noise.', '[]'::jsonb),
  ('coda-ai', 'AI built into Coda docs.', '[]'::jsonb),
  ('soundful', 'AI music for creators.', '[]'::jsonb),
  ('browser-use', 'Open-source browser agent framework.', '[]'::jsonb),
  ('brave-leo', 'Brave''s private search with AI answers.', '[]'::jsonb),
  ('studyfetch', 'Turns course materials into flashcards and an AI tutor.', '[]'::jsonb),
  ('lex', 'AI word processor.', '[]'::jsonb),
  ('artisan', 'AI BDR named Ava.', '[]'::jsonb),
  ('alli-ai', 'Automated website SEO.', '[]'::jsonb),
  ('genie-ai', 'AI legal document drafting.', '[]'::jsonb),
  ('woebot', 'AI mental health companion.', '[]'::jsonb),
  ('juicebox', 'AI talent search (PeopleGPT).', '[]'::jsonb),
  ('ramp', 'AI finance automation.', '[]'::jsonb),
  ('whimsical', 'Flowcharts and mind maps with AI.', '[]'::jsonb),
  ('heygen-translate', 'AI subtitles, transcription and dubbing.', '[]'::jsonb),
  ('looker-gemini', 'Google''s BI platform with Gemini.', '[]'::jsonb),
  ('ollama', 'Tool for running open-source LLMs locally.', '[]'::jsonb),
  ('voiceflow', 'Platform for collaboratively designing AI agents.', '[]'::jsonb),
  ('recraft', 'Generates vector graphics and brand-consistent images.', '[]'::jsonb),
  ('10web', 'AI WordPress website builder.', '[]'::jsonb),
  ('zed', 'High-performance collaborative code editor with AI.', '[]'::jsonb),
  ('sloyd', 'Parametric 3D model generation.', '[]'::jsonb),
  ('captions', 'App for AI captions, dubbing and video editing.', '[]'::jsonb),
  ('vtube-studio', 'Virtual avatar streaming software.', '[]'::jsonb),
  ('auphonic', 'Automatic audio post-production.', '[]'::jsonb),
  ('evernote-ai', 'Note-taking app with AI search.', '[]'::jsonb),
  ('splash', 'AI music games and creation.', '[]'::jsonb),
  ('genspark', 'AI super agent and search.', '[]'::jsonb),
  ('kagi', 'Ad-free paid search engine with AI.', '[]'::jsonb),
  ('magicschool', 'AI tool platform for teachers.', '[]'::jsonb),
  ('novelai', 'AI story writing and anime-style image generation.', '[]'::jsonb),
  ('salesforce-agentforce', 'Salesforce''s AI agent platform.', '[]'::jsonb),
  ('profound', 'Tracks brand visibility in AI answers.', '[]'::jsonb),
  ('heidi', 'AI medical scribe.', '[]'::jsonb),
  ('leena-ai', 'AI employee service agent.', '[]'::jsonb),
  ('cleo', 'AI personal finance assistant.', '[]'::jsonb),
  ('miro-ai', 'Collaborative whiteboard with AI.', '[]'::jsonb),
  ('timekettle', 'AI simultaneous translation earbuds.', '[]'::jsonb),
  ('formula-bot', 'AI Excel formulas and data analysis.', '[]'::jsonb),
  ('lm-studio', 'Desktop app for downloading and running local LLMs.', '[]'::jsonb),
  ('manychat', 'Instagram/Messenger auto-replies and AI marketing.', '[]'::jsonb),
  ('clipdrop', 'Suite of AI image editing tools.', '[]'::jsonb),
  ('wix-ai', 'Wix''s AI website builder.', '[]'::jsonb),
  ('kiro', 'AWS''s spec-driven AI IDE.', '[]'::jsonb),
  ('blockade-labs', 'Generates 360-degree skybox environments.', '[]'::jsonb),
  ('wondershare-filmora', 'Desktop video editor with AI features.', '[]'::jsonb),
  ('akool', 'AI face swap and digital avatars.', '[]'::jsonb),
  ('podcastle', 'AI podcast recording and editing.', '[]'::jsonb),
  ('obsidian-copilot', 'Local Markdown notes that can be paired with AI plugins.', '[]'::jsonb),
  ('tunee', 'AI music creation tool.', '[]'::jsonb),
  ('operator-skyvern', 'Automates browser workflows with AI.', '[]'::jsonb),
  ('andi', 'Conversational search.', '[]'::jsonb),
  ('brisk', 'AI Chrome extension for teachers.', '[]'::jsonb),
  ('novelcrafter', 'Novel planning and AI writing.', '[]'::jsonb),
  ('seamless-ai', 'AI contact search.', '[]'::jsonb),
  ('suki', 'Voice AI assistant for physicians.', '[]'::jsonb),
  ('lattice-ai', 'Talent management with AI.', '[]'::jsonb),
  ('docyt', 'AI bookkeeping automation.', '[]'::jsonb),
  ('eraser', 'AI technical diagrams and docs.', '[]'::jsonb),
  ('interprefy', 'AI live interpretation for meetings.', '[]'::jsonb),
  ('gptexcel', 'Copilot built into Excel.', '[]'::jsonb),
  ('typingmind', 'Advanced LLM chat interface where you bring your own API keys.', '[]'::jsonb),
  ('crisp', 'Customer messaging platform with AI.', '[]'::jsonb),
  ('picsart-ai', 'Photo and video editing platform with AI features.', '[]'::jsonb),
  ('brandmark', 'AI logo design.', '[]'::jsonb),
  ('trae', 'ByteDance''s AI IDE.', '[]'::jsonb),
  ('move-ai', 'Markerless AI motion capture.', '[]'::jsonb),
  ('haiper', 'AI video generation.', '[]'::jsonb),
  ('facefusion', 'Open-source face swap tool.', '[]'::jsonb),
  ('riverside', 'Remote recording and AI editing.', '[]'::jsonb),
  ('reflect', 'Networked note-taking with AI.', '[]'::jsonb),
  ('mureka', 'AI song generation from Kunlun Tech.', '[]'::jsonb),
  ('multion', 'Autonomous web agent.', '[]'::jsonb),
  ('komo', 'AI search engine.', '[]'::jsonb),
  ('curipod', 'Generates interactive AI lessons.', '[]'::jsonb),
  ('shortlyai', 'English writing style checker.', '[]'::jsonb),
  ('instantly', 'Cold email outreach with AI.', '[]'::jsonb),
  ('seo-ai-yoast', 'WordPress SEO plugin with AI.', '[]'::jsonb),
  ('viz-ai', 'AI for medical imaging and care coordination.', '[]'::jsonb),
  ('vic-ai', 'AI accounts payable automation.', '[]'::jsonb),
  ('mapify', 'Turns content into AI mind maps.', '[]'::jsonb),
  ('sheetai', 'AI add-on for Google Sheets.', '[]'::jsonb),
  ('librechat', 'Open-source multi-model chat interface.', '[]'::jsonb),
  ('kore-ai', 'Enterprise conversational AI platform.', '[]'::jsonb),
  ('fotor', 'Online AI photo editing and design tool.', '[]'::jsonb),
  ('logoai', 'AI logo and brand design.', '[]'::jsonb),
  ('qodo', 'AI code review and test generation.', '[]'::jsonb),
  ('vidu', 'Video generation model from ShengShu Technology.', '[]'::jsonb),
  ('synthesys', 'AI voices and avatar videos.', '[]'::jsonb),
  ('lalal', 'AI vocal and instrument separation.', '[]'::jsonb),
  ('heptabase', 'Whiteboard-style knowledge management with AI.', '[]'::jsonb),
  ('agentgpt', 'Autonomous agents in the browser.', '[]'::jsonb),
  ('iask', 'Free AI question-answering search.', '[]'::jsonb),
  ('speak', 'AI English speaking practice.', '[]'::jsonb),
  ('languagetool', 'Multilingual grammar checker.', '[]'::jsonb),
  ('smartlead', 'Cold email automation.', '[]'::jsonb),
  ('datarails', 'FP&A platform with AI.', '[]'::jsonb),
  ('xmind-ai', 'Mind mapping software with AI.', '[]'::jsonb),
  ('quadratic', 'AI-powered programmable spreadsheet.', '[]'::jsonb),
  ('open-webui', 'Self-hostable web interface for LLMs.', '[]'::jsonb),
  ('landbot', 'No-code chatbot builder.', '[]'::jsonb),
  ('pixlr', 'Online AI photo editor.', '[]'::jsonb),
  ('interior-ai', 'AI interior design redesigns.', '[]'::jsonb),
  ('coderabbit', 'AI code review for pull requests.', '[]'::jsonb),
  ('deepmotion', 'Turns video into 3D animation.', '[]'::jsonb),
  ('pixverse', 'AI video generation platform.', '[]'::jsonb),
  ('moises', 'Music stem separation and practice app.', '[]'::jsonb),
  ('tana', 'Structured note-taking with AI.', '[]'::jsonb),
  ('autogpt', 'Open-source autonomous agent platform.', '[]'::jsonb),
  ('metaso', 'Ad-free AI search from China.', '[]'::jsonb),
  ('praktika', 'Language learning with AI avatar tutors.', '[]'::jsonb),
  ('hemingway', 'Editor that improves readability.', '[]'::jsonb),
  ('chorus', 'AI sales call notes and CRM updates.', '[]'::jsonb),
  ('beautiful-tables', 'Presentations and infographics with AI.', '[]'::jsonb),
  ('deepnote', 'AI data notebook.', '[]'::jsonb),
  ('jan', 'Open-source offline ChatGPT alternative.', '[]'::jsonb),
  ('gorgias', 'E-commerce customer service platform with AI agents.', '[]'::jsonb),
  ('roomgpt', 'Upload a photo of a room to generate a new interior design.', '[]'::jsonb),
  ('greptile', 'AI code review that understands your codebase.', '[]'::jsonb),
  ('rokoko', 'Free AI motion capture.', '[]'::jsonb),
  ('genmo', 'Open-source Mochi video model.', '[]'::jsonb),
  ('rev', 'AI and human transcription services.', '[]'::jsonb),
  ('craft', 'Polished documents with an AI assistant.', '[]'::jsonb),
  ('uipath', 'Enterprise RPA and agentic automation.', '[]'::jsonb),
  ('storm', 'Stanford''s tool for generating Wikipedia-style research articles.', '[]'::jsonb),
  ('elsa', 'AI English pronunciation coach.', '[]'::jsonb),
  ('typeface', 'Enterprise brand content generation.', '[]'::jsonb),
  ('pipedrive-ai', 'CRM with an AI assistant.', '[]'::jsonb),
  ('mode', 'SQL and BI platform.', '[]'::jsonb),
  ('monica', 'Browser AI assistant extension that integrates multiple models.', '[]'::jsonb),
  ('dante-ai', 'Train custom AI chatbots on your data.', '[]'::jsonb),
  ('dreamina', 'ByteDance CapCut''s AI image and video generation.', '[]'::jsonb),
  ('vectorizer', 'Converts raster images to vectors.', '[]'::jsonb),
  ('scenario', 'AI asset generation for game art.', '[]'::jsonb),
  ('ltx-studio', 'Lightricks'' AI storyboarding and video production.', '[]'::jsonb),
  ('assemblyai', 'Speech recognition and understanding API.', '[]'::jsonb),
  ('saner', 'ADHD-friendly AI notes.', '[]'::jsonb),
  ('power-automate', 'Microsoft''s workflow automation with Copilot.', '[]'::jsonb),
  ('mathgpt', 'AI math problem solving.', '[]'::jsonb),
  ('copysmith', 'AI social media post generation and scheduling.', '[]'::jsonb),
  ('vanna', 'Open-source text-to-SQL.', '[]'::jsonb),
  ('merlin', 'Multi-model AI assistant in the browser.', '[]'::jsonb),
  ('jotform-ai', 'Jotform''s AI customer service agents.', '[]'::jsonb),
  ('tengr', 'AI image generation tool.', '[]'::jsonb),
  ('patterned', 'AI seamless pattern generation.', '[]'::jsonb),
  ('warp', 'Terminal with AI agents.', '[]'::jsonb),
  ('higgsfield', 'AI video with cinematic camera-movement effects.', '[]'::jsonb),
  ('deepgram', 'Speech-to-text and voice AI APIs.', '[]'::jsonb),
  ('superhuman', 'AI-accelerated email client.', '[]'::jsonb),
  ('microsoft-copilot-studio', 'Microsoft''s platform for building custom agents.', '[]'::jsonb),
  ('turnitin', 'Plagiarism and AI writing detection.', '[]'::jsonb),
  ('predis', 'AI social media post and ad generation.', '[]'::jsonb),
  ('ai2sql', 'Generates SQL from natural language.', '[]'::jsonb),
  ('sider', 'Sidebar AI assistant extension.', '[]'::jsonb),
  ('imagine-art', 'AI image and video generation platform.', '[]'::jsonb),
  ('fontjoy', 'AI graphic and T-shirt design.', '[]'::jsonb),
  ('factory', 'Enterprise AI software development agents (Droids).', '[]'::jsonb),
  ('moonvalley', 'Video model trained on licensed data.', '[]'::jsonb),
  ('cartesia', 'Low-latency speech synthesis models.', '[]'::jsonb),
  ('shortwave', 'AI Gmail client.', '[]'::jsonb),
  ('activepieces', 'Open-source automation platform.', '[]'::jsonb),
  ('gptzero', 'Detection of AI-generated text.', '[]'::jsonb),
  ('adcreative', 'AI ad creative generation.', '[]'::jsonb),
  ('chatsonic', 'Writesonic''s AI chat assistant.', '[]'::jsonb),
  ('starryai', 'Mobile AI art generation app.', '[]'::jsonb),
  ('penpot', 'Free AI stock image library.', '[]'::jsonb),
  ('augment', 'AI assistant for large codebases.', '[]'::jsonb),
  ('wan', 'Alibaba''s open-weight video model.', '[]'::jsonb),
  ('hume', 'Voice AI with emotional understanding.', '[]'::jsonb),
  ('spark-mail', 'Email app with AI.', '[]'::jsonb),
  ('pipedream', 'Integration and agent platform for developers.', '[]'::jsonb),
  ('copyleaks', 'AI and plagiarism detection.', '[]'::jsonb),
  ('pencil', 'Generative advertising platform.', '[]'::jsonb),
  ('displayr', 'Survey data analysis with AI.', '[]'::jsonb),
  ('replika', 'AI companion chat app.', '[]'::jsonb),
  ('artbreeder', 'Creative tool for blending and generating images.', '[]'::jsonb),
  ('blackbox', 'AI code generation and search.', '[]'::jsonb),
  ('leonardo-motion', 'AI video generation and editing.', '[]'::jsonb),
  ('vapi', 'Platform for building voice AI agents.', '[]'::jsonb),
  ('clockwise', 'AI calendar optimization.', '[]'::jsonb),
  ('langsmith', 'Tracing and evaluation for LLM applications.', '[]'::jsonb),
  ('quizgecko', 'AI quiz question generation.', '[]'::jsonb),
  ('hootsuite-owlywriter', 'Social media management with OwlyWriter AI.', '[]'::jsonb),
  ('browse-ai', 'No-code web data extraction.', '[]'::jsonb),
  ('janitor-ai', 'Roleplay chat platform.', '[]'::jsonb),
  ('deep-dream-generator', 'AI art generation community.', '[]'::jsonb),
  ('codeium', 'Free AI code completion (now part of Windsurf).', '[]'::jsonb),
  ('vmake', 'AI video and images for e-commerce.', '[]'::jsonb),
  ('bland', 'AI phone agents for customer service.', '[]'::jsonb),
  ('sunsama', 'Daily planning tool.', '[]'::jsonb),
  ('dust', 'Enterprise AI agent platform.', '[]'::jsonb),
  ('gradescope', 'AI-assisted grading.', '[]'::jsonb),
  ('buffer-ai', 'Social media scheduling with an AI assistant.', '[]'::jsonb),
  ('firecrawl', 'Turns websites into LLM-ready data.', '[]'::jsonb),
  ('nomi', 'AI companion app with memory.', '[]'::jsonb),
  ('comfyui', 'Open-source node-based workflow tool for diffusion models.', '[]'::jsonb),
  ('mutable', 'AI long-term memory assistant for developers.', '[]'::jsonb),
  ('retell', 'Platform for AI phone voice agents.', '[]'::jsonb),
  ('akiflow', 'Combined tasks and calendar.', '[]'::jsonb),
  ('mem0', 'Memory layer for AI agents.', '[]'::jsonb),
  ('coursebox', 'AI online course builder.', '[]'::jsonb)
) as v(id, description_en, key_features_en)
where t.id = v.id
  and (t.description_en is null or btrim(t.description_en) = '' or t.key_features_en is null or t.key_features_en = '[]'::jsonb);

-- search_tsv：若定義尚未包含 description_en 才重建（重複執行不會重建）
do $$
begin
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'ai_tools' and column_name = 'search_tsv'
      and generation_expression ilike '%description_en%'
  ) then
    alter table public.ai_tools drop column if exists search_tsv;
    alter table public.ai_tools add column search_tsv tsvector
      generated always as (
        to_tsvector('simple'::regconfig,
          coalesce(name,'') || ' ' || coalesce(description_zh,'') || ' ' || coalesce(description_en,'') || ' ' ||
          coalesce(category,'') || ' ' || coalesce(subcategory,'') || ' ' || coalesce(tags::text,''))
      ) stored;
  end if;
end $$;
create index if not exists ai_tools_search_idx on public.ai_tools using gin (search_tsv);

alter table public.diagnoses add column if not exists locale text not null default 'zh';
do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'diagnoses_locale_check') then
    alter table public.diagnoses add constraint diagnoses_locale_check check (locale in ('zh', 'en'));
  end if;
end $$;
create index if not exists diagnoses_tool_locale_idx on public.diagnoses (tool_id, locale, created_at desc);

commit;

-- 檢查：select count(*) filter (where description_en is not null) as en_rows, count(*) as total from public.ai_tools;
